language: rust

rust:
  - nightly-2020-08-13

git:
  depth: 5

addons:
  firefox: latest
  chrome: stable

env:
  global:
    - CARGO_TARGET_DIR=$HOME/.cargo/target
    - secure: D1PFf/A6KVOEzVWTOrCINwrF3q1J9pFL4MXNI/0/pteWWUlUctgp5Pt0LpeLJglyx8qtsO7BPmiuVNHXhObCLaFkz2+9TNL5hqz7RkMbJA9PPgSlzt9NxY5puhE9RtKKCJ0L7Xb9F7Ft+8ujds9qLlzpSrXfDCzdFTROblT1eRiRZAcueXbHGol9P7lJsE52Nns22cmThmlKFQIaYwQDtnhNHuDjQCnfAGCPrPNrbmxOYyk8X5RgThgeSoX/Fwsnm6Tdt7c9dL3fh8Rcxu7Dje+wh1cEG1QMeyXxFJ1XJfB0Yi5ZK8zGXg+KqR6EwedOcoxf04yEQdWQXB9J+g613KPuX2covMzt/+fDx3vREN0vAMVREDXV0YclA7JPcN8lTE6w/GhOA7/Qi8Zmbzu9SYPfR2HsCSeeBd8u/zaeCC0AB0gI75TzUr6+YpJewYuUG3eXL5+L9eAE+fg0hOoeWzr9cgNnlT/xz27XuGbatQkzkuuXcHClPwPgLwiFoDbzFGW0i1gxGZ787R/UQJBfKmbDtDys6P9B/ZP9eO82lxPMvfCnBf9fEan2vvsX1rmAvt4GqjEuMZ21hP++y16xRHTaxxFpsPwh9beJWCLhs/V/t6Kmv5Oao7JnOqzTzo5BnE1hCkoIHXyg2YNBW/q0EgOUPHBzbjPA6TnKSM70VI0=
    - secure: HR94JH0kioiY3VK6+9Cs9LHA2uWs9nqWmX0gq1pjjU98Z7E/sPM54bBqsZBCd/odeou3BUotOSs/90DnS6Eedrcv6lb84Q7Lc7Pj+uZL/hafKyi4sz78COzHJliX9T57y0YwCtygiD7XP/h41yWPZDXznmoyAxcKg4c7/a9qs4JAEORVks9gNZ0Mt8T5KKWqqx33pTouACppWmiRbJBcwXhe8nS03QAr3w41xdAerhAGC8jLqWY6eWRDjQ8pDMqUD0KTHzsOBzbjXdXajUpS67bFHGiSsEsoErsgCp9frarlbs0JPcDpa035on9iYMwBVNaF5SmGwT5PqEmL1tiVa08wy13/H60H7eTqNEb9hweg9vpLc/t2Msba4DZ6fAZKNs6ohd2q3QOXUjI2h9DK3TYqINqfxQSIIksdw8i3H+Dbez1Cn2lsTxLzAHm8RyarG4T6QQBeCOEbcfDdUhckZgNd7c5rPjqj6TWP2BB8RiQfCv8A/6qLhZF3IRfYTBU6KQRNFFrvLeuoH26SJV70cKe5PQE/I760VZ/KTRAKXp11a3jBEVeuLEEzCiTGkZxAjwOMoBhEJ+rry2vVESTxv8ASy/XTXfY1qvW6elj1Tz2efvKuhNc+ry/4jHZVvJ+260InzGCOZ88XgnaUU08jJqIO6wmi7yB7VqDXoBDF1dE=

install:
  - mkdir -p ~/.cargo/target
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 14
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh || true
  - cargo install cargo-whatfeatures --no-default-features --features "rustls"
  - export LIB_VERSION=$(cat Cargo.toml | grep version | head -1 | sed 's/[",(version = )]//g')
  - echo LIB_VERSION=$LIB_VERSION
  - export NPM_VERSION_EXISTS=$(./npm_version_exists.sh $LIB_VERSION)
  - echo NPM_VERSION_EXISTS=$NPM_VERSION_EXISTS
  - export CRATE_VERSION_EXISTS=$(NO_COLOR=1 ./crate_version_exists.sh $LIB_VERSION)
  - echo CRATE_VERSION_EXISTS=$CRATE_VERSION_EXISTS

cache: cargo

stages:
  - check
  - test
  - deploy

jobs:
  include:
    - stage: check
      script: cargo check
    - script: cargo check --target wasm32-unknown-unknown
    - script: cargo check --features save
    - script: cargo check --target wasm32-unknown-unknown --features save
    - script: cargo check --no-default-features
    - script: cargo check --target wasm32-unknown-unknown --no-default-features
    - script: cargo check --no-default-features --features save
    - script: cargo check --target wasm32-unknown-unknown --no-default-features --features save
    - stage: test
      script: yarn test
      name: Test WASM
    - script: cargo test
      name: Test Rust
    - stage: deploy
      script: echo "deploying to NPM..."
      name: Deploy to NPM
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash npm_deploy.sh
    - script: echo "deploying to crates.io..."
      name: Deploy to Crates.io
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash crate_deploy.sh
